name: Build

on:
  - push

env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Context: $Env:CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache nuget
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/*.props') }}
        restore-keys: nuget-

    - name: Build
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --no-build

    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: |
          **/*.nupkg
          **/*.snupkg

    - name: Publish packages
      run: |
        dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
