name: Build

on:
  push:
    branches:
      - master

env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

jobs:
  deploy-docs:
    runs-on: windows-latest
    steps:

    - name: Dump context
      env:
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Context: $Env:CONTEXT"

    - name: Determine cache fallbacks
      if: github.event_name != 'push'
      id: cache_fallbacks
      run: |
        echo "::set-output name=nuget::nuget-"

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache nuget
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/*.props') }}
        restore-keys: ${{ steps.cache_fallbacks.outputs.nuget }}

    - name: Build
      run: |
        mkdir public
        dotnet build --configuration Release
        dotnet tool install xmldocmd -g
        Copy-Item pages/* public -Recurse
        xmldocmd .\src\Faithlife.NestEmbedder.EmbeddedAssemblyLoader\bin\Release\netstandard2.0\Faithlife.NestEmbedder.EmbeddedAssemblyLoader.dll public

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public